let
    Source = Excel.Workbook(File.Contents("E:\KRS_Learning Video\Data_File\Sample - Superstore.xlsx"), null, true),
    SuperStore_Table = Source{[Item="SuperStore",Kind="Table"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(SuperStore_Table,{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}}),
    #"RegionSQ#" = Table.AddColumn(#"Changed Type", "RegionSQ#", each if [Region] = "Central" then 1 else if [Region] = "West" then 2 else if [Region] = "East" then 3 else 4),
    #"Duplicated Column" = Table.DuplicateColumn(#"RegionSQ#", "Customer Name", "Customer Name - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Customer Name - Copy", "First_Name"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns", "First_Name", "First_Name - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"First_Name - Copy", "Last_Name"}}),
    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Renamed Columns1", {{"Last_Name", each Text.AfterDelimiter(_, " "), type text}}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Extracted Text After Delimiter", {{"First_Name", each Text.BeforeDelimiter(_, " "), type text}}),
    #"Added Conditional Column" = Table.AddColumn(#"Extracted Text Before Delimiter", "Custom", each if [Segment] = "Home Office" then "HO" else if [Segment] = "Corporate" then "CP" else if [Segment] = "Consumer" then "CN" else "Null"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Custom", type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Custom", "Short_Name_Segment"}}),
    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns2", "Custom", each if [Short_Name_Segment] = "HO" then 1 else if [Short_Name_Segment] = "CO" then 2 else if [Short_Name_Segment] = "CN" then 3 else 4),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Custom", Int64.Type}})
in
    #"Changed Type2"